<a href="https://colab.research.google.com/github/EJG2000/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
x =  np.random.random((3,3))
print(x)

[[0.45871966 0.39197713 0.10954137]
 [0.36839271 0.90431265 0.16852885]
 [0.45290775 0.52636959 0.77318196]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np

arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(1,17).reshape(4,4)

print("Generating Array")
print(arr1,end="\n\n")

print("Reshaping array")
arr1_mod = arr1.reshape(2,8)
arr2_mod = arr2.reshape(2,8)
print(arr1_mod,end="\n\n")

print("Verticaly stacking")
V_stack = np.vstack((arr1_mod,arr2_mod))
print(V_stack,end="\n\n")

print("Horizontally stacking")
H_stack = np.hstack((arr1_mod,arr2_mod))
print(H_stack,end="\n\n")

Generating Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Reshaping array
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

Verticaly stacking
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

Horizontally stacking
[[ 1  2  3  4  5  6  7  8  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16  9 10 11 12 13 14 15 16]]

